### ISSUE TITLE
Command line arg parsing not work properly when I want to add a password (using hidden text)

### ISSUE THREAD

**Issue by samthebest** [sniptt-official/snip-cli#5]
`snip add joebloggs_aws_password_prod -v aws_initial_passwords`

`snip add joebloggs_aws_password_test --vault aws_initial_passwords`

Also, moving the `--vault` not work either, nor adding the value as non-hidden text at the end.

```
snip --vault aws_initial_passwords add joebloggs_aws_password_test 1234
Error: Unknown argument: 1234
Hint: Use the --help option to get help about the usage
```

**Comment by rogerthebest** [comment]
This has been fixed by https://github.com/sniptt-official/snip-cli/commit/cf1c3fd5844d2f8dde21c6dec04c95bfa1a78a57. The issue was incorrectly parsing the global --version / -v flag.
